vim.keymap.set("n", "Y", "yy")
vim.keymap.set("n", "<leader>/", ":noh<CR>")
vim.keymap.set("n", "<leader>H", ":split<CR>")
vim.keymap.set("n", "<leader>V", ":vsplit<CR>")
vim.keymap.set('n', '<leader>bd', ':%bw<CR>', { noremap = true, silent = true })
