[font]
size = 15.0

[font.normal]
family = "Lilex Nerd Font Mono"
style = "Regular"

[window]
decorations = "None"
startup_mode = "Maximized"

[colors.primary]
background = "#000000"

[general]
import = ["alacritty.local.toml"]
